name: CortexCI

on:
  repository_dispatch:
    types: [cortex-ci]

env:
  # Unity credentials
  UNITY_EMAIL: ${{ secrets.CORTEX_UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.CORTEX_UNITY_PASSWORD }}
  UNITY_SERIAL: ${{ secrets.CORTEX_UNITY_SERIAL }}

  # Apple credentials
  APPLE_CONNECT_EMAIL: ${{ secrets.CORTEX_APPLE_CONNECT_EMAIL }}
  APPLE_DEVELOPER_EMAIL: ${{ secrets.CORTEX_APPLE_DEVELOPER_EMAIL }}
  APPLE_DEVELOPER_TEAM_ID: ${{ secrets.CORTEX_APPLE_DEVELOPER_TEAM_ID }}
  APPLE_CONNECT_TEAM_ID: ${{ secrets.CORTEX_APPLE_CONNECT_TEAM_ID }}
  APPSTORE_ISSUER_ID: ${{ secrets.CORTEX_APPSTORE_ISSUER_ID }}
  APPSTORE_P8: ${{ secrets.CORTEX_APPSTORE_P8 }}
  APPSTORE_KEY_ID: ${{ secrets.CORTEX_APPSTORE_KEY_ID }}

  # Code signing
  MATCH_URL: ${{ secrets.CORTEX_CERTIFICATES_REPO_URL }}
  MATCH_PASSWORD: ${{ secrets.CORTEX_CERTIFICATES_PASSWORD }}
  MATCH_PAT: ${{ secrets.CORTEX_CERTIFICATES_PAT }}
  MATCH_PAT_EMAIL: ${{ secrets.CORTEX_CERTIFICATES_PAT_EMAIL }}

  # Android signing
  ANDROID_KEYSTORE_NAME: ${{ secrets.CORTEX_ANDROID_KEYSTORE_NAME }}
  ANDROID_KEYSTORE_BASE64: ${{ secrets.CORTEX_ANDROID_KEYSTORE_BASE64 }}
  ANDROID_KEYSTORE_PASS: ${{ secrets.CORTEX_ANDROID_KEYSTORE_PASS }}
  ANDROID_KEYALIAS_NAME: ${{ secrets.CORTEX_ANDROID_KEYALIAS_NAME }}
  ANDROID_KEYALIAS_PASS: ${{ secrets.CORTEX_ANDROID_KEYALIAS_PASS }}

jobs:
  build-unity:
    name: unity
    runs-on: gf-ubuntu-8core
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.client_payload.build.ref }}
          token: ${{ secrets.CORTEX_COMPANY_GITHUB_TOKEN }}
          submodules: true
          lfs: true

      - name: Checkout Cortex CI Core
        uses: actions/checkout@v6
        with:
          repository: gameflexteam/cortex-ci-core
          ref: ${{ github.event.client_payload.ciVersion }}
          token: ${{ secrets.CORTEX_CI_CORE_TOKEN }}
          path: ./.github/cortex

      - name: Build Unity
        uses: ./.github/cortex/actions/build-unity
        with:
          targetPlatform: ${{ github.event.client_payload.build.targetPlatform }}
          environment: ${{ github.event.client_payload.build.environment }}
          gameBuildId: ${{ github.event.client_payload.game.buildId }}
          gameVersion: ${{ github.event.client_payload.game.version }}
          gameBuildNumber: ${{ github.event.client_payload.game.buildNumber }}
          appIdentifier: ${{ github.event.client_payload.build.appIdentifier }}
          gameName: ${{ github.event.client_payload.game.name }}
          gameBuildMode: ${{ github.event.client_payload.build.buildMode }}
          cortexApiSecret: ${{ github.event.client_payload.cortexApiSecret }}
          diawiToken: ${{ secrets.CORTEX_DIAWI_TOKEN }}
          storageCredentials: ${{ secrets.CORTEX_GCP_CREDENTIALS }}
          googlePlayServiceAccount: ${{ secrets.CORTEX_GOOGLE_PLAY_SERVICE_ACCOUNT }}
          gameId: ${{ github.event.client_payload.game.id }}
          androidUploadPlaystore: ${{ github.event.client_payload.build.uploadPlayStore }}
          metadataLanguages: ${{ github.event.client_payload.build.metadataLanguages }}

  build-xcode:
    name: xcode
    runs-on: macos-15-xlarge
    needs: build-unity
    if: ${{ github.event.client_payload.build.targetPlatform == 'iOS' }}
    steps:
      - name: Checkout Cortex CI Core
        uses: actions/checkout@v6
        with:
          repository: gameflexteam/cortex-ci-core
          ref: ${{ github.event.client_payload.ciVersion }}
          token: ${{ secrets.CORTEX_CI_CORE_TOKEN }}
          path: ./.github/cortex

      - name: Build Xcode
        uses: ./.github/cortex/actions/build-xcode
        with:
          cortexApiSecret: ${{ github.event.client_payload.cortexApiSecret }}
          environment: ${{ github.event.client_payload.build.environment }}
          gameBuildId: ${{ github.event.client_payload.game.buildId }}
          gameBuildMode: ${{ github.event.client_payload.build.buildMode }}
          gameVersion: ${{ github.event.client_payload.game.version }}
          gameBuildNumber: ${{ github.event.client_payload.game.buildNumber }}
          appIdentifier: ${{ github.event.client_payload.build.appIdentifier }}
          diawiToken: ${{ secrets.CORTEX_DIAWI_TOKEN }}
          diskCleanUp: 'true'
          xcodeVersion: ${{ github.event.client_payload.build.xcodeVersion }}
